In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns

In [6]:
df=pd.read_csv("train.csv",parse_dates=["Date"],index_col=[0])

In [7]:
print(df.index.freq)

None


In [8]:
df.shape

(5203, 5)

In [9]:
df.head()

Open        High         Low       Close   Adj Close
Date                                                                  
2001-01-25  356.730774  362.980774  352.403839  353.365387  197.122452
2001-01-26  357.211548  360.096161  342.788452  343.269226  191.490234
2001-01-29  345.153839  355.769226  338.461548  341.384613  190.439011
2001-01-30  344.307678  355.923065  341.692322  355.769226  198.463318
2001-01-31  359.615387  361.153839  350.461548  353.692322  197.304749

In [10]:
df.tail()

Open        High         Low       Close   Adj Close
Date                                                                  
2021-09-23   99.529999  104.080002   99.519997  102.959999  102.789993
2021-09-24  102.660004  104.199997  102.599998  103.800003  103.709198
2021-09-27  104.550003  106.330002  104.389999  105.349998  105.257835
2021-09-28  105.290001  106.750000  104.730003  105.730003  105.637512
2021-09-29  106.000000  107.000000  105.309998  106.279999  106.187027

In [11]:
test_split=round(len(df)*0.20)

In [12]:
test_split

1041

In [13]:
df_for_training=df[:-1041]
df_for_testing=df[-1041:]

In [14]:
print(df_for_training.shape)
print(df_for_testing.shape)

(4162, 5)
(1041, 5)


In [15]:
scaler = MinMaxScaler(feature_range=(0,1))
df_for_training_scaled = scaler.fit_transform(df_for_training)

In [16]:
df_for_testing_scaled=scaler.transform(df_for_testing)

In [17]:
df_for_training_scaled

array([[0.85398707, 0.86281807, 0.85292546, 0.8403402 , 0.82180889],
       [0.85533406, 0.85473269, 0.82623316, 0.8122593 , 0.79289309],
       [0.82155169, 0.84260459, 0.81422168, 0.80701755, 0.78749611],
       ...,
       [0.40689652, 0.40362224, 0.41960282, 0.40436458, 0.7632948 ],
       [0.40517242, 0.39995691, 0.41832161, 0.4075738 , 0.76889077],
       [0.40862067, 0.39974127, 0.41426436, 0.39880189, 0.75359571]])

In [18]:
df_for_training_scaled.shape

(4162, 5)

In [19]:
df_for_testing_scaled.shape

(1041, 5)

In [20]:
def createXY(dataset,n_past):
    dataX = []
    dataY = []
    for i in range(n_past, len(dataset)):
            dataX.append(dataset[i - n_past:i, 0:dataset.shape[1]])
            dataY.append(dataset[i,0])
    return np.array(dataX),np.array(dataY)        

In [21]:
trainX,trainY=createXY(df_for_training_scaled,30)

In [22]:
trainX.shape

(4132, 30, 5)

In [23]:
testX,testY=createXY(df_for_testing_scaled,30)

In [24]:
trainX[0]

array([[0.85398707, 0.86281807, 0.85292546, 0.8403402 , 0.82180889],
       [0.85533406, 0.85473269, 0.82623316, 0.8122593 , 0.79289309],
       [0.82155169, 0.84260459, 0.81422168, 0.80701755, 0.78749611],
       [0.81918098, 0.84303579, 0.82319031, 0.8470261 , 0.8286929 ],
       [0.86206895, 0.85769729, 0.84753366, 0.84124952, 0.8227448 ],
       [0.85668106, 0.85295391, 0.85479397, 0.84659822, 0.82825271],
       [0.85129307, 0.85661925, 0.85372629, 0.84766796, 0.82935384],
       [0.8540948 , 0.88249248, 0.85799703, 0.88125807, 0.86394198],
       [0.88577588, 0.88227684, 0.88255396, 0.87590928, 0.85843431],
       [0.88189657, 0.87602422, 0.87016871, 0.86200256, 0.84411479],
       [0.88362063, 0.88357053, 0.87892376, 0.86606763, 0.84829995],
       [0.87047413, 0.86200956, 0.84390347, 0.8344031 , 0.81569511],
       [0.83857758, 0.87645542, 0.84966903, 0.87398378, 0.85645156],
       [0.88168102, 0.88012075, 0.88105913, 0.86649551, 0.84874037],
       [0.87090514, 0.86287196, 0.

In [25]:
print("trainX Shape-- ",trainX.shape)
print("trainY Shape-- ",trainY.shape)

trainX Shape--  (4132, 30, 5)
trainY Shape--  (4132,)


In [26]:
print("testX Shape-- ",testX.shape)
print("testY Shape-- ",testY.shape)

testX Shape--  (1011, 30, 5)
testY Shape--  (1011,)


In [27]:
print("trainX[0]-- \n",trainX[0])
print("\ntrainY[0]-- ",trainY[0])

trainX[0]-- 
 [[0.85398707 0.86281807 0.85292546 0.8403402  0.82180889]
 [0.85533406 0.85473269 0.82623316 0.8122593  0.79289309]
 [0.82155169 0.84260459 0.81422168 0.80701755 0.78749611]
 [0.81918098 0.84303579 0.82319031 0.8470261  0.8286929 ]
 [0.86206895 0.85769729 0.84753366 0.84124952 0.8227448 ]
 [0.85668106 0.85295391 0.85479397 0.84659822 0.82825271]
 [0.85129307 0.85661925 0.85372629 0.84766796 0.82935384]
 [0.8540948  0.88249248 0.85799703 0.88125807 0.86394198]
 [0.88577588 0.88227684 0.88255396 0.87590928 0.85843431]
 [0.88189657 0.87602422 0.87016871 0.86200256 0.84411479]
 [0.88362063 0.88357053 0.87892376 0.86606763 0.84829995]
 [0.87047413 0.86200956 0.84390347 0.8344031  0.81569511]
 [0.83857758 0.87645542 0.84966903 0.87398378 0.85645156]
 [0.88168102 0.88012075 0.88105913 0.86649551 0.84874037]
 [0.87090514 0.86287196 0.85949177 0.84724008 0.82891342]
 [0.85237065 0.88249248 0.8601324  0.88403941 0.86680588]
 [0.85668106 0.86589053 0.86248134 0.8630723  0.84521599]


In [28]:
trainY[0]

0.8297413960482309

In [29]:
trainY.shape

(4132,)

In [3]:
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import GridSearchCV

ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'

In [8]:
!pip install

ERROR: Could not find a version that satisfies the requirement keras.wrappers (from versions: none)
ERROR: No matching distribution found for keras.wrappers


In [6]:
def build_model(optimizer):
    grid_model = Sequential()
    grid_model.add(LSTM(50,return_sequences=True,input_shape=(30,5)))
    grid_model.add(LSTM(50))
    grid_model.add(Dropout(0.2))
    grid_model.add(Dense(1))

    grid_model.compile(loss = 'mse',optimizer = optimizer)
    return grid_model

grid_model = KerasRegressor(build_fn=build_model,verbose=1,validation_data=(testX,testY))
parameters = {'batch_size' : [16,20],
              'epochs' : [8,10],
              'optimizer' : ['adam','Adadelta'] }

grid_search  = GridSearchCV(estimator = grid_model,
                            param_grid = parameters,
                            cv = 2)

NameError: name 'KerasRegressor' is not defined

In [28]:
grid_search = grid_search.fit(trainX,trainY)

Epoch 1/8
130/130 [==============================] - 6s 23ms/step - loss: 0.0045 - val_loss: 0.0024
Epoch 2/8
130/130 [==============================] - 2s 17ms/step - loss: 0.0012 - val_loss: 0.0017
Epoch 3/8
130/130 [==============================] - 2s 18ms/step - loss: 9.0876e-04 - val_loss: 0.0014
Epoch 4/8
130/130 [==============================] - 2s 17ms/step - loss: 8.8440e-04 - val_loss: 0.0016
Epoch 5/8
130/130 [==============================] - 2s 18ms/step - loss: 8.2294e-04 - val_loss: 0.0018
Epoch 6/8
130/130 [==============================] - 2s 18ms/step - loss: 7.0709e-04 - val_loss: 0.0013
Epoch 7/8
130/130 [==============================] - 2s 18ms/step - loss: 8.3741e-04 - val_loss: 0.0011
Epoch 8/8
130/130 [==============================] - 1s 6ms/step - loss: 0.0061
Epoch 1/8
130/130 [==============================] - 6s 25ms/step - loss: 0.0111 - val_loss: 0.0011
Epoch 2/8
130/130 [==============================] - 3s 19ms/step - loss: 0.0029 - val_loss: 5.4374e

207/207 [==============================] - 4s 20ms/step - loss: 0.0014 - val_loss: 2.0823e-04
Epoch 6/8
207/207 [==============================] - 4s 20ms/step - loss: 0.0014 - val_loss: 1.4749e-04
Epoch 7/8
207/207 [==============================] - 4s 20ms/step - loss: 0.0013 - val_loss: 1.3235e-04
Epoch 8/8
207/207 [==============================] - 4s 20ms/step - loss: 0.0012 - val_loss: 1.1994e-04


In [29]:
grid_search.best_params_

{'batch_size': 20, 'epochs': 8, 'optimizer': 'adam'}

In [30]:
my_model=grid_search.best_estimator_.model

In [31]:
my_model

In [32]:
prediction=my_model.predict(testX)

In [33]:
print("prediction\n", prediction)
print("\nPrediction Shape-",prediction.shape)

prediction
 [[0.36429983]
 [0.36749688]
 [0.37060487]
 ...
 [0.1306538 ]
 [0.13263184]
 [0.13514471]]

Prediction Shape- (1011, 1)


In [34]:
prediction.shape

(1011, 1)

In [35]:
scaler.inverse_transform(prediction)

ValueError: non-broadcastable output operand with shape (1011,1) doesn't match the broadcast shape (1011,5)

In [36]:
prediction_copies_array = np.repeat(prediction,5, axis=-1)

In [37]:
prediction_copies_array.shape

(1011, 5)

In [38]:
prediction_copies_array

array([[0.36429983, 0.36429983, 0.36429983, 0.36429983, 0.36429983],
       [0.36749688, 0.36749688, 0.36749688, 0.36749688, 0.36749688],
       [0.37060487, 0.37060487, 0.37060487, 0.37060487, 0.37060487],
       ...,
       [0.1306538 , 0.1306538 , 0.1306538 , 0.1306538 , 0.1306538 ],
       [0.13263184, 0.13263184, 0.13263184, 0.13263184, 0.13263184],
       [0.13514471, 0.13514471, 0.13514471, 0.13514471, 0.13514471]],
      dtype=float32)

In [39]:
pred=scaler.inverse_transform(np.reshape(prediction_copies_array,(len(prediction),5)))[:,0]

In [40]:
pred

array([181.9501  , 183.09119 , 184.20052 , ...,  98.556435,  99.26244 ,
       100.15935 ], dtype=float32)

In [41]:
original_copies_array = np.repeat(testY,5, axis=-1)

original_copies_array.shape

original=scaler.inverse_transform(np.reshape(original_copies_array,(len(testY),5)))[:,0]

In [42]:
pred

array([181.9501  , 183.09119 , 184.20052 , ...,  98.556435,  99.26244 ,
       100.15935 ], dtype=float32)

In [43]:
print("Pred Values-- " ,pred)
print("\nOriginal Values-- ",original)

Pred Values--  [181.9501   183.09119  184.20052  ...  98.556435  99.26244  100.15935 ]

Original Values--  [191.692307 193.461533 192.307693 ... 104.550003 105.290001 106.      ]


In [44]:
import matplotlib.pyplot as plt

In [45]:
plt.plot(original, color = 'red', label = 'Real  Stock Price')
plt.plot(pred, color = 'blue', label = 'Predicted  Stock Price')
plt.title(' Stock Price Prediction')
plt.xlabel('Time')
plt.ylabel(' Stock Price')
plt.legend()
plt.show()

In [99]:
df_30_days_past=df.iloc[-30:,:]

In [100]:
df_30_days_past

Open        High         Low       Close   Adj Close
Date                                                                  
2021-08-18  101.080002  103.470001  100.760002  101.410004  101.242561
2021-08-19  100.000000  100.820000   98.599998   99.419998   99.255844
2021-08-20   99.589996  100.669998   99.099998  100.050003   99.884804
2021-08-23  100.599998  101.480003  100.269997  100.970001  100.803284
2021-08-24  101.290001  103.510002  101.059998  103.269997  103.099487
2021-08-25  103.360001  105.129997  102.550003  104.699997  104.527122
2021-08-26  104.459999  104.620003  102.839996  103.379997  103.209305
2021-08-27  103.900002  106.150002  103.900002  106.089996  105.914825
2021-08-30  106.330002  106.459999  104.800003  105.190002  105.016312
2021-08-31  104.940002  106.360001  104.459999  105.410004  105.235954
2021-09-01  105.360001  105.470001  103.260002  103.660004  103.488846
2021-09-02  104.000000  106.339996  103.980003  106.260002  106.084557
2021-09-03  106.000000  107.360001  104.080002  104.750000  104.577042
2021-09-07  104.500000  104.940002  102.309998  103.290001  103.119453
2021-09-08  102.949997  104.730003  100.419998  102.580002  102.410629
2021-09-09  102.360001  104.919998  102.110001  103.290001  103.119453
2021-09-10  103.290001  103.949997  101.779999  102.000000  101.831581
2021-09-13  102.650002  104.860001  102.019997  104.459999  104.287521
2021-09-14  104.540001  104.550003  100.070000  100.379997  100.214256
2021-09-15  100.790001  102.470001  100.690002  102.160004  101.991325
2021-09-16  102.389999  102.699997  100.820000  101.339996  101.172668
2021-09-17  101.150002  101.860001  100.129997  100.470001  100.304115
2021-09-20   98.500000   99.870003   97.269997   99.809998   99.645195
2021-09-21   99.900002   99.989998   96.209999   96.820000   96.660133
2021-09-22   97.669998   99.029999   97.660004   98.540001   98.377296
2021-09-23   99.529999  104.080002   99.519997  102.959999  102.789993
2021-09-24  102.660004  104.199997  102.599998  103.800003  103.709198
2021-09-27  104.550003  106.330002  104.389999  105.349998  105.257835
2021-09-28  105.290001  106.750000  104.730003  105.730003  105.637512
2021-09-29  106.000000  107.000000  105.309998  106.279999  106.187027

In [103]:
df_30_days_future=pd.read_csv("test.csv",parse_dates=["Date"],index_col=[0])
df_30_days_future.shape

(30, 4)

In [112]:
df_30_days_future

Open        High         Low       Close   Adj Close
Date                                                            
2021-09-30     0  107.089996  102.949997  103.029999  102.939865
2021-10-01     0  106.389999  103.669998  105.820000  105.727425
2021-10-04     0  107.080002  104.599998  104.900002  104.808235
2021-10-05     0  106.000000  103.750000  104.900002  104.808235
2021-10-06     0  104.419998  102.059998  104.330002  104.238731
2021-10-07     0  106.529999  104.330002  105.510002  105.417702
2021-10-08     0  106.220001  104.660004  104.720001  104.628387
2021-10-11     0  105.760002  103.970001  104.080002  103.988953
2021-10-12     0  104.040001  101.559998  102.720001  102.630142
2021-10-13     0  103.199997  101.180000  102.360001  102.270454
2021-10-14     0  103.650002  102.370003  102.739998  102.650116
2021-10-15     0  105.900002  103.190002  104.410004  104.318665
2021-10-18     0  104.570000  103.040001  104.120003  104.028915
2021-10-19     0  104.970001  103.580002  104.730003  104.638382
2021-10-20     0  106.019997  103.870003  106.000000  105.907272
2021-10-21     0  106.389999  103.010002  103.150002  103.059761
2021-10-22     0  104.510002  102.550003  104.050003  103.958977
2021-10-25     0  105.989998  103.330002  105.300003  105.207886
2021-10-26     0  110.970001  105.220001  107.440002  107.346008
2021-10-27     0  108.279999  103.690002  103.849998  103.759148
2021-10-28     0  105.379997  103.099998  105.260002  105.167915
2021-10-29     0  105.239998  104.120003  104.870003  104.778259
2021-11-01     0  106.769997  105.279999  106.230003  106.137070
2021-11-02     0  107.139999  105.300003  106.690002  106.596664
2021-11-03     0  106.339996  104.820000  105.970001  105.877296
2021-11-04     0  106.400002  104.290001  105.209999  105.117958
2021-11-05     0  109.650002  106.849998  108.739998  108.644867
2021-11-08     0  110.309998  108.320000  108.419998  108.325150
2021-11-09     0  116.169998  110.480003  111.290001  111.192642
2021-11-10     0  112.680000  108.110001  108.959999  108.864677

In [104]:
df_30_days_future["Open"]=0
df_30_days_future=df_30_days_future[["Open","High","Low","Close","Adj Close"]]
old_scaled_array=scaler.transform(df_30_days_past)
new_scaled_array=scaler.transform(df_30_days_future)
new_scaled_df=pd.DataFrame(new_scaled_array)
new_scaled_df.iloc[:,0]=np.nan
full_df=pd.concat([pd.DataFrame(old_scaled_array),new_scaled_df]).reset_index().drop(["index"],axis=1)

In [105]:
full_df.shape

(60, 5)

In [106]:
full_df.tail()

0         1         2         3         4
55 NaN  0.143640  0.164162  0.150135  0.349458
56 NaN  0.152749  0.171268  0.159953  0.367565
57 NaN  0.154599  0.175349  0.159063  0.365924
58 NaN  0.171024  0.181345  0.167045  0.380645
59 NaN  0.161242  0.174766  0.160565  0.368694

In [107]:
full_df.shape

(60, 5)

In [114]:
full_df_scaled_array=full_df.values

In [115]:
full_df_scaled_array.shape

(60, 5)

In [116]:
all_data=[]
time_step=30
for i in range(time_step,len(full_df_scaled_array)):
    data_x=[]
    data_x.append(full_df_scaled_array[i-time_step:i,0:full_df_scaled_array.shape[1]])
    data_x=np.array(data_x)
    prediction=my_model.predict(data_x)
    all_data.append(prediction)
    full_df.iloc[i,0]=prediction

In [117]:
all_data

[array([[0.1378213]], dtype=float32),
 array([[0.13945529]], dtype=float32),
 array([[0.14068112]], dtype=float32),
 array([[0.14162877]], dtype=float32),
 array([[0.14216018]], dtype=float32),
 array([[0.14206707]], dtype=float32),
 array([[0.1421535]], dtype=float32),
 array([[0.14225037]], dtype=float32),
 array([[0.14217126]], dtype=float32),
 array([[0.14150538]], dtype=float32),
 array([[0.14047278]], dtype=float32),
 array([[0.13954498]], dtype=float32),
 array([[0.13914707]], dtype=float32),
 array([[0.13891666]], dtype=float32),
 array([[0.13893819]], dtype=float32),
 array([[0.13930015]], dtype=float32),
 array([[0.13948296]], dtype=float32),
 array([[0.13946058]], dtype=float32),
 array([[0.13963053]], dtype=float32),
 array([[0.14062819]], dtype=float32),
 array([[0.14126904]], dtype=float32),
 array([[0.14153312]], dtype=float32),
 array([[0.1416432]], dtype=float32),
 array([[0.14201452]], dtype=float32),
 array([[0.14254372]], dtype=float32),
 array([[0.14292328]], dtype

In [118]:
new_array=np.array(all_data)
new_array=new_array.reshape(-1,1)
prediction_copies_array = np.repeat(new_array,5, axis=-1)
y_pred_future_30_days = scaler.inverse_transform(np.reshape(prediction_copies_array,(len(new_array),5)))[:,0]

In [119]:
y_pred_future_30_days

array([101.11468 , 101.69789 , 102.135414, 102.473656, 102.66332 ,
       102.6301  , 102.66094 , 102.69551 , 102.66728 , 102.4296  ,
       102.06105 , 101.7299  , 101.58788 , 101.50563 , 101.51332 ,
       101.64251 , 101.70776 , 101.69977 , 101.76044 , 102.11652 ,
       102.34525 , 102.43951 , 102.478806, 102.61133 , 102.80022 ,
       102.93569 , 102.98711 , 103.2831  , 103.732796, 104.54266 ],
      dtype=float32)

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model

In [ ]:
mymodel.save('Model_future_value.h5')
print('Model Saved!')

In [ ]:
scaler

In [ ]:
import pickle
scalerfile = 'scaler_model_future_value.pkl'
pickle.dump(scaler, open(scalerfile, 'wb'))

# END!!!!